// <auto-generated />
using System;
using ControleAlunos.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleAlunos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240209194028_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ControleAlunos.Api.Entities.Alunos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("NomePaiOuMae")
                        .HasColumnType("longtext");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistroId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Endereco = "Rua Augusto Mendes Pinto - 164",
                            Idade = 29,
                            Nome = "Lucas",
                            NomePaiOuMae = "Iraneide Rocha",
                            TurmaId = 1
                        });
                });

            modelBuilder.Entity("ControleAlunos.Api.Entities.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int?>("AlunoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("AlunoNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AlunoTurma")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("Presenca")
                        .IsRequired()
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Registro");
                });

            modelBuilder.Entity("ControleAlunos.Api.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("NomeDaTurma")
                        .HasColumnType("longtext");

                    b.Property<string>("Professor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RegistroId");

                    b.ToTable("Turma");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeDaTurma = "Natação",
                            Professor = "Sebastião",
                            Turno = "Manhã"
                        });
                });

            modelBuilder.Entity("ControleAlunos.Api.Entities.Alunos", b =>
                {
                    b.HasOne("ControleAlunos.Api.Entities.Registro", "Registro")
                        .WithMany("Alunos")
                        .HasForeignKey("RegistroId");

                    b.HasOne("ControleAlunos.Api.Entities.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("ControleAlunos.Api.Entities.Turma", b =>
                {
                    b.HasOne("ControleAlunos.Api.Entities.Registro", null)
                        .WithMany("Turmas")
                        .HasForeignKey("RegistroId");
                });

            modelBuilder.Entity("ControleAlunos.Api.Entities.Registro", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("ControleAlunos.Api.Entities.Turma", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
